#!/bin/bash
NAME=PersonalWebsite
DIR=.
USER=erikucenik
WORKERS=5
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/venv/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error

mkdir -p $DIR/run
source $VENV
exec gunicorn main:app \
	--name $NAME \
	--workers $WORKERS \
	--worker-class $WORKER_CLASS \
	--user=$USER \
#	--group=$GROUP \
	--bind=$BIND \
	--log-level=$LOG_LEVEL \
	--log-file=-
